estimator: imblearn.ensemble.BalancedRandomForestClassifier
oversampling: False
one_hot: True
hyperparams_grid:
  n_estimators: [50, 100, 200, 400, 700]
  criterion: 'gini'
  max_depth: [ 10, 20, 50, 100, null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: [50, 100, 300, 500, 800]
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  bootstrap: True
  oob_score: True
  sampling_strategy: 'not minority'
  replacement: True
  warm_start: False #can be useful to speed up the computation
  class_weight: null
  ccp_alpha: 0.0 #to prune