estimator: sklearn.naive_bayes.CategoricalNB
oversampling: True
one_hot: False
hyperparams_grid:
  alpha: [0.01, 0.1, 0.5, 1, 5, 10, 30, 50, 80, 100]
  force_alpha: True
  fit_prior: True
  class_prior: null
  min_categories: [10]