estimator: sklearn.svm.SVC
oversampling: True
one_hot: True
hyperparams_grid:
  C: [0.0001, 0.0005, 0.001, 0.01, 0.1, 1, 10, 50]
  gamma: [0.0001, 0.0005, 0.001, 0.01, 0.1, 1, 10, 50, 'scale']
  kernel: ['rbf']
  class_weight: null
  shrinking: True
  probability: False
  tol: 0.001
  cache_size: 200
  max_iter: -1
  decision_function_shape: 'ovr'
  break_ties: False